import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ABOUT_ME_CONTENT } from '../src/data/aboutMeContent.ts';
import { CONTACT } from '../src/data/contact.ts';
import { PROJECTS_CONTENT } from '../src/data/projectsContent.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const PORTFOLIO_URL = 'https://martinvesely.netlify.app';
const LINKEDIN_URL = 'https://www.linkedin.com/in/veselymartin-online/';
const CV_SUBTITLE = 'Junior Software Developer';

// CVs are always generated in Czech, regardless of the site's language switcher.
const aboutMeContent = ABOUT_ME_CONTENT.cs;
const projectsContent = PROJECTS_CONTENT.cs;

/** Sections already covered by `about-me.cs.md` — same as on the About page. */
const IGNORED_ABOUT_SECTIONS = new Set(['Dovednosti', 'Koníčky']);

const EDUCATION_SECTION_TITLE = 'Vzdělání, práce a brigády v IT';

function readRootFile(relativePath: string): string {
  return readFileSync(join(rootDir, relativePath), 'utf8');
}

function normalizeAboutMeMarkdown(raw: string): string {
  return raw
    .replace(/\*\*<u>([^<]+)<\/u>\*\*/g, '#### $1')
    .replace(/<\/?u>/g, '')
    .replace(/^##### /gm, '### ')
    .trim();
}

function normalizeWorkApproachMarkdown(raw: string): string {
  return raw
    .split(/<br\s*\/?>/gi)
    .map((part) => part.replace(/^>\s*/gm, '').trim())
    .filter((part) => part.length > 0)
    .map((part) => `> ${part}`)
    .join('\n>\n');
}

function stripMarkdownInline(text: string): string {
  return text.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\*([^*]+)\*/g, '$1');
}

function formatPhone(phone: string): string {
  const digits = phone.replace(/\D/g, '');
  if (digits.length !== 12 || !digits.startsWith('420')) {
    return phone;
  }

  return `+${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6, 9)} ${digits.slice(9)}`;
}

function formatHeader(): string {
  return [
    '<img src="cv-assets/photo_of_me.jpg" class="cv-photo" alt="Martin Veselý" />',
    '',
    `## Martin Veselý - ${CV_SUBTITLE}`,
    '',
    `Pro více informací najdeš na: ${PORTFOLIO_URL}`,
  ].join('\n');
}

function formatEducationCardHeading(card: { title: string; linkLabel: string }): string {
  if (card.linkLabel === 'Commity') {
    return `#### ${card.title}`;
  }

  return `#### ${card.title} - ${card.linkLabel}`;
}

function formatEducationSection(): string {
  const section = aboutMeContent.sections.find(
    (item) => 'cards' in item && item.title === EDUCATION_SECTION_TITLE,
  );

  if (!section || !('cards' in section)) {
    throw new Error(`Missing "${EDUCATION_SECTION_TITLE}" in ABOUT_ME_CONTENT`);
  }

  const lines = [`### ${section.title}`, ''];

  for (const card of section.cards) {
    lines.push(formatEducationCardHeading(card), '');

    for (const bullet of card.bullets) {
      lines.push(`- ${stripMarkdownInline(bullet)}`);
    }

    if (card.references && card.references.length > 0) {
      lines.push('', '**Reference:**', '');

      for (const quote of card.references) {
        lines.push(`- „${stripMarkdownInline(quote)}“`);
      }
    }

    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

function formatProjectsSection(): string {
  const lines = [`## ${projectsContent.title}`, ''];

  for (const card of projectsContent.cards) {
    const [firstBullet, ...restBullets] = card.bullets;
    lines.push(`#### ${card.title} - ${firstBullet.strong}`, '');
    lines.push(`- ${firstBullet.strong}${firstBullet.normal}`);

    for (const bullet of restBullets) {
      lines.push(`- ${bullet.strong}${bullet.normal}`);
    }

    lines.push(`- Web: ${card.websiteLinkHref}`);
    lines.push(`- Repo: ${card.githubLinkHref}`);
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

function formatContactSection(): string {
  return [
    '## Kontakt',
    '',
    `- Email: ${CONTACT.email.address}`,
    `- Telefon / WhatsApp: ${formatPhone(CONTACT.whatsapp.phone)}`,
    `- GitHub: ${CONTACT.github.href}`,
    `- LinkedIn: ${LINKEDIN_URL}`,
  ].join('\n');
}

function buildCvMarkdown(): string {
  const aboutMe = normalizeAboutMeMarkdown(readRootFile('src/content/about-me.cs.md'));
  const workApproach = normalizeWorkApproachMarkdown(
    readRootFile('src/content/work-approach.cs.md'),
  );
  const ignoredSections = [...IGNORED_ABOUT_SECTIONS].sort().join(', ');

  return [
    '<!-- Generated by `pnpm cv:generate`. Edit source content files instead. -->',
    `<!-- Ignored duplicate About sections: ${ignoredSections} -->`,
    '',
    formatHeader(),
    '',
    '## O mně',
    '',
    aboutMe,
    '',
    formatEducationSection(),
    '',
    formatProjectsSection(),
    '',
    '## Spolupráce a způsob práce',
    '',
    workApproach,
    '',
    formatContactSection(),
    '',
  ].join('\n');
}

const outputPath = join(rootDir, 'cv', 'vesely_martin_cv.md');
writeFileSync(outputPath, buildCvMarkdown(), 'utf8');
console.log(`Wrote ${outputPath}`);
